languageCode = "ru"
languageName = "Russian"
weight = 20
title = "Arkaev"

[params]
  displayName = "RU"
  isoCode = "ru"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "/img/avatar.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
